- name: Install apache, php and mariadb for Ubuntu
  tags: apache, mariadb, php, ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
      - mariadb-server
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install apache, php and mariadb for CentOS
  tags: apache, mariadb, php, centos
  dnf:
    name:
      - httpd
      - php
      - mariadb-server
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: Mariadb - Restarting/ Enabling
  service:
    name: mariadb
    state: restarted
    enabled: true
